### ISSUE TITLE
Criar perfis em redes sociais

### ISSUE THREAD

**Issue by jwnx** [LivreCamp/documentos#2]
Oi pessoal,

Até o momento temos dois canais de comunicação/divulgação, que são o Telegram e o Github. No entanto, como queremos alcançar um público maior, eles não são suficiente. Precisamos aumentar nossa presença nas redes sociais pra atrair mais pessoas e principalmente os calouros.

Segue uma lista de possíveis canais:

- Facebook (página)
- Meetup
- Algo que divulgue fotos
- IRC (?)

Sugestões?

**Comment by jose-victor** [comment]
Além dessas coisas podemos divulgar as atividades nos emails acadêmicos. No IMECC é bem simples, só pedir que já repassam. No IC não sei como funciona pra divulgar essas coisas.

Dependendo da atividade podemos ir na DAC pra ver como faz pra divulgar pra todo mundo da graduação da Unicamp. Imagino que se um professor pedir pra divulgar seja mais fácil, mas a gente deve conseguir também.

**Comment by jwnx** [comment]
No IC também é bem simples. Podemos até falar com a Islene e talvez ela nos ajude com a divulgação dentro do Instituto. Da Unicamp toda eu já não sei, mas podemos perguntar. 

O único problema disso no IC é que a gente recebe muito e-mail diariamente na lista dos alunos. Talvez os nossos avisos/mensagens passem despercebidos. ):

**Comment by victorgcapone** [comment]
Sob o risco de aumentar nosso trabalho consideravelmente, podíamos ter um blog,

**Comment by leoyvens** [comment]
Vocês certamente deveriam entrar em contato com a Islene, na aula de seminários em software livre ela lamentou o fim do GPSL, ela vai ficar feliz em saber que vocês existem. Se quiserem fazer alguma palestra na disciplina serão bem vindos pois ela está buscando palestrantes.

**Comment by jwnx** [comment]
@leodasvacas A gente já discutiu conversar com a professora Islene mil vezes. Alguns membros do grupo fizeram a disciplina de Seminários em SL semestre passado com ela e sabemos que ela é uma linda. Acho que tá na hora de entrarmos efetivamente em contato, mas acho difícil darmos alguma palestra porque estamos muito enrolados com os eventos do grupo esse semestre. (:

**Comment by victorgcapone** [comment]
Outra coisa que precisamos urgentemente, uma conta no google.

**Comment by jwnx** [comment]
@victorgcapone você diz um email?

**Comment by victorgcapone** [comment]
@jwnx Tambem, na vdd isso me veio agora fazendo o forms, precisamos de um drive e um docs (na vdd eu n sei se temos, temos?) para centralizar esses documentos que estamos criando, por exemplo, resultados de pesquisas, apresentações ppt etc...

**Comment by jwnx** [comment]
@victorgcapone atualmente a gente tenta fazer isso aqui no repositório mesmo. Documentos de texto a gente só commita. Coisas como apresentações e links externos a gente coloca no README. Falta, inclusive, colocarmos os slides da apresentação de ontem. A gente pode abordar o assunto de criar uma conta num serviço de cloud em uma das reuniões e ver o que o pessoal acha (:

**Comment by victorgcapone** [comment]
@jwnx Então, mas mesmo tendo links externos, acho que fica um pouco complicado a gente distribuir esse tipo de coisa pelos nossos drives pessoais, vamos tentar falar disso hoje, não acho que teremos alguém contra isso, mas enfim, podemos aproveitar e discutir todo esse ticket.

**Comment by victorgcapone** [comment]
Acontece que criamos uma pasta compartilhada e duas agendas no google, uma de eventos públicos (palestras, cursos, etc...) e outra "administrativa" para marcamos reuniões e etc...

**Comment by victorgcapone** [comment]
Eu crieir a página no face: https://www.facebook.com/LivreCamp/, e acho que por enquanto é o único canal que precisamos, posso matar esse issue?

**Comment by jwnx** [comment]
Podemos matar! Melhor usar o Facebook como canal principal por enquanto mesmo.
