### ISSUE TITLE
Verificar possibilidade de apresentar a palestra para calouros do cursão

### ISSUE THREAD

**Issue by victorgcapone** [LivreCamp/documentos#3]
Alguém que possa conversar com o coordenador de graduação ou com o professor da disciplina relevante para levantar a possibilidade de um palestra?
Primeiro precisamos saber a disicipla e quem é o coordenador do curso.

**Comment by victorgcapone** [comment]
Tentei dar uma olhada no catálogo do curso 51 e não encontrei as matérias do cruso básico, alguém tem detalhes sobre isso?
@jwnx @samchenatti @murilocruz @andrealmeid @henriquefacioli ?

**Comment by andrealmeid** [comment]
Dá pra ver usando o GDE:

​

2017-03-14 21:45 GMT-03:00 victorgcapone <notifications@github.com>:

**Comment by victorgcapone** [comment]
Agora que FM003 é a disciplina Seminários sobre a Profissão e que possívelmente é a disciplina que queremos! O Próximo passo é descobrir quem é o professor responsável e mandar-lhe um email.

**Comment by victorgcapone** [comment]
Aqui é trabalho! Emails enviados! Segue uma cópia pra quem quiser ver:

Boa tarde, Professor

Meu nome é Victor Capone, sou aluno de graduação do IC e ajudo na organização do LivreCamp, um grupo pró-cultura livre criado recentemente. Estamos organizando eventos para divulgar a filosofia de software livre por todo o campus, incluindo um curso de 3 dias sobre linux, um Installfest de 2 dias para ajudar os calouros interessados a instalarem linux em seus computadores e um curso de R no IMECC.
Gostaríamos de saber se o senhor tem interesse/disponibilidade de nos ceder um seminário na sua disciplina de Seminários sobre a Profissão (FM003) para abordar o assunto de software livre, segurança e privacidade.

Grato desde já,

Victor Capone
livrecamp.org

**Comment by victorgcapone** [comment]
O Professor Abner, da física respondeu ao email: 

Caro Vitor, tudo bem?

De fato a iniciativa é excelente. Infelizmente eu já comprometi todos  
os dias com palestras de professores convidados.
Por outro lado, poderíamos pensar em marcar um dia na hora do almoço  
um seminário e abrir para toda a comunidade de alunos, não somente  
para os bixos.. Poderia ser no auditório do IFGW.

Att.,

Abner

**Comment by victorgcapone** [comment]
Oi Victor,

Por favor procure a secretaria de graduação para organizar a reserva  
da sala e possível divulgação.
Sugiro que voces façam os cartazes e tragam. Podemos afixar. Também  
podemos colocar um aviso de oportunidade nas nossas páginas.
Att.,

Abner

**Comment by jose-victor** [comment]
Que tipo de atividade seria feita?

**Comment by victorgcapone** [comment]
@jose-victor Seria uma palestra de apresentação da LivreCamp + O que é software livre o @murilocruz junto com a Akari vão preparar

**Comment by andrealmeid** [comment]
@victorgcapone, conseguiram dar a palestra no cursão?
