### ISSUE TITLE
Procurar palestrante que nos divulgue na Secomp

### ISSUE THREAD

**Issue by victorgcapone** [LivreCamp/documentos#4]
Precisamos procurar gente que nos divulgue durante a secomp, com quem podemos falar sobre isso?

**Comment by jwnx** [comment]
Não voltamos a falar disso. Se encontrarem alguém da Secomp, podem levantar essa bola pra eu saber se ainda é necessário correr atrás dessa tarefa? @victorgcapone @samchenatti

**Comment by andrealmeid** [comment]
Esta issue é referente à Secomp 2017.
