### ISSUE TITLE
Pré-evento SECOMP (LivreCamp+Encripta)

### ISSUE THREAD

**Issue by victorgcapone** [LivreCamp/documentos#5]
Conseguimos espaço no pré-evento da Secomp e precisamos organizar direitinho o que queremos fazer, o pessoal da encripta vem junto para fazermos uma coisa bacana!

**Comment by jwnx** [comment]
@jose-victor tá no grupo aqui do github também. (:

**Comment by victorgcapone** [comment]
Esse é o doc da nossa proposta formal para a comissão da SECOMP, tambem é um resumo da reunião que tivemos hj (eu, @samchenatti , @jose-victor e akari):
https://docs.google.com/document/d/1SE1z_i6VRorLkn3ZvDuFdlLqBavq0fAdOkzkHTCqZZw/edit

**Comment by jose-victor** [comment]
Tá pedindo pra ter conta do google pra acessar, tem que ter mesmo?

**Comment by victorgcapone** [comment]
@jose-victor acho que não preciso não

**Comment by victorgcapone** [comment]
@jose-victor e outros: https://pad.riseup.net/p/PreEventoSecomp Um link com a proposta no Riseup Pad

**Comment by andrealmeid** [comment]
O pré-evento ocorreu! O tema foi "Ciência Livre", e ocorreu na dia 04/05/2017, no Auditório do IC3. Conseguimos engajar docentes da Unicamp a compartilhar a experiência do uso de software livre na academia.

**Comment by andrealmeid** [comment]
Vídeo do evento: https://www.youtube.com/watch?v=uBQy7SH8U_I
